### ISSUE TITLE
Error when trying to run adaptive_grid

### ISSUE THREAD

**Issue by Mary-Wall** [usnistgov/SDNist#3]
I was trying to run
`python adaptive_grid.py`

and I got this error:
```
Traceback (most recent call last):
  File "adaptive_grid.py", line 4, in <module>
    from util import discretize, undo_discretize, downward_closure
  File "C:\Users\mary_\SDNist\examples\Minutemen\util.py", line 3, in <module>
    from mbi import Domain, Dataset
ModuleNotFoundError: No module named 'mbi'
```

**Comment by glothe** [comment]
You're probably missing Minutemen's `private-pgm`library [()](https://github.com/ryan112358/private-pgm). This is the library that actually does the heavy lifting.

**Comment by Mary-Wall** [comment]
Gregoire, 
Thank you for pointing me to that library.  It also looks like `SDNist/examples/Minutemen/adaptive_grid.py` may have been updated, as the content of `nist-synthetic-data-2021/extensions/adaptive_grid.py ` differs.  The adaptive_grid.py file in the `nist-synthetic-data-2021` library, seems to extend to arbitrary data sets.
