### ISSUE TITLE
Should float columns be binned in the K-marginal score?

### ISSUE THREAD

**Issue by AwesomeLemon** [usnistgov/SDNist#31]
Hi, 

I'm interested in the K-marginal score. In the implementation (https://github.com/usnistgov/SDNist/blob/main/sdnist/metrics/kmarginal.py), I'm not seeing that the float values are binned. Are they binned in some other place in the code, or not at all? If they are not binned anywhere, why is that?

My reasoning is that without binning, creating marginals via df.groupby leads to unique points for any marginal that includes a float value: e.g., records (0, 1, 0.05) and (0, 1, 0.05000001) would be considered distinct and count as errors in synthetic data, decreasing the metric value. This seems undesirable to me since the probability of getting exactly equal float values is vanishingly small. Binning the float values would address this issue.

I would appreciate if if you could help me better understand this matter.

**Comment by kbtriangulum** [comment]
We do bin the numerical features before evaluating them with K-marginal. But we don't transform them inside the k-marginal metric code. We do it once at one place to make the transformed data available for other metrics as well.

Here is the snippet that prepares the binned data: https://github.com/usnistgov/SDNist/blob/main/sdnist/report/dataset/__init__.py#L214
And here is the call to kmarginal metric with binned data: https://github.com/usnistgov/SDNist/blob/main/sdnist/report/score/utility/__init__.py#L572

**Comment by AwesomeLemon** [comment]
Thank you for the explanation!
